Open Detection: SiftGPU Class Reference
SiftGPU Class Reference
#include <SiftGPU.h>
Classes
struct SiftKeypoint
Public Types
enum { SIFTGPU_NOT_SUPPORTED = 0, SIFTGPU_PARTIAL_SUPPORTED = 1, SIFTGPU_FULL_SUPPORTED = 2 }
typedef struct
SiftGPU::SiftKeypoint SiftKeypoint
Public Member Functions
const char * GetCurrentImagePath ()
virtual SIFTGPU_EXPORT void SetImageList (int nimage, const char **filelist)
virtual SIFTGPU_EXPORT int GetFeatureNum ()
virtual SIFTGPU_EXPORT void SaveSIFT (const char *szFileName)
virtual SIFTGPU_EXPORT void GetFeatureVector (SiftKeypoint *keys, float *descriptors)
virtual SIFTGPU_EXPORT void SetKeypointList (int num, const SiftKeypoint *keys, int keys_have_orientation=1)
virtual SIFTGPU_EXPORT int CreateContextGL ()
virtual SIFTGPU_EXPORT int VerifyContextGL ()
virtual SIFTGPU_EXPORT int IsFullSupported ()
virtual SIFTGPU_EXPORT void SetVerbose (int verbose=4)
void SetVerboseBrief ()
virtual SIFTGPU_EXPORT void ParseParam (int argc, char **argv)
virtual SIFTGPU_EXPORT int RunSIFT (const char *imgpath)
virtual SIFTGPU_EXPORT int RunSIFT (int index)
virtual SIFTGPU_EXPORT int RunSIFT (int width, int height, const void *data, unsigned int gl_format, unsigned int gl_type)
virtual SIFTGPU_EXPORT int RunSIFT ()
virtual SIFTGPU_EXPORT int RunSIFT (int num, const SiftKeypoint *keys, int keys_have_orientation=1)
SIFTGPU_EXPORT SiftGPU (int np=1)
virtual SIFTGPU_EXPORT ~SiftGPU ()
virtual SIFTGPU_EXPORT void SetActivePyramid (int index)
virtual SIFTGPU_EXPORT int GetImageCount ()
virtual SIFTGPU_EXPORT void SetTightPyramid (int tight=1)
virtual SIFTGPU_EXPORT int AllocatePyramid (int width, int height)
virtual SIFTGPU_EXPORT void SetMaxDimension (int sz)
SIFTGPU_EXPORT void * operator new (size_t size)
Public Member Functions inherited from SiftParam
void ParseSiftParam ()
float GetLevelSigma (int lev)
float GetInitialSmoothSigma (int octave_min)
SIFTGPU_EXPORT SiftParam ()
Public Attributes
float _timing [10]
Public Attributes inherited from SiftParam
float * _sigma
float _sigma_skip0
float _sigma_skip1
float _sigma0
float _sigman
int _sigma_num
int _dog_level_num
int _level_num
int _level_min
int _level_max
int _level_ds
float _dog_threshold
float _edge_threshold
Protected Member Functions
void InitSiftGPU ()
void LoadImageList (const char *imlist)
Static Protected Member Functions
static void PrintUsage ()
Protected Attributes
int _current
int _initialized
int _image_loaded
char * _imgpath
char * _outpath
ImageList * _list
GLTexInput * _texImage
SiftPyramid * _pyramid
Detailed Description
Definition at line 97 of file SiftGPU.h.
Member Typedef Documentation
typedef struct SiftGPU::SiftKeypoint SiftGPU::SiftKeypoint
Member Enumeration Documentation
anonymous enum
Enumerator
SIFTGPU_NOT_SUPPORTED
SIFTGPU_PARTIAL_SUPPORTED
SIFTGPU_FULL_SUPPORTED
Definition at line 100 of file SiftGPU.h.
Constructor & Destructor Documentation
SIFTGPU_EXPORT SiftGPU::SiftGPU (int np = 1)
virtual SIFTGPU_EXPORT SiftGPU::~SiftGPU () virtual
Member Function Documentation
virtual SIFTGPU_EXPORT int SiftGPU::AllocatePyramid (int width, int height) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT int SiftGPU::CreateContextGL () virtual
Reimplemented in ServerSiftGPU.
const char* SiftGPU::GetCurrentImagePath () inline
Definition at line 139 of file SiftGPU.h.
References _imgpath.
virtual SIFTGPU_EXPORT int SiftGPU::GetFeatureNum () virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT void SiftGPU::GetFeatureVector (SiftKeypoint * keys, float * descriptors) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT int SiftGPU::GetImageCount () virtual
Reimplemented in ServerSiftGPU.
void SiftGPU::InitSiftGPU () protected
virtual SIFTGPU_EXPORT int SiftGPU::IsFullSupported () virtual
Reimplemented in ServerSiftGPU.
void SiftGPU::LoadImageList (const char * imlist) protected
SIFTGPU_EXPORT void* SiftGPU::operator new (size_t size)
virtual SIFTGPU_EXPORT void SiftGPU::ParseParam (int argc, char ** argv) virtual
Reimplemented in ServerSiftGPU.
Referenced by od::ODFeatureDetector2D::ODFeatureDetector2D().
static void SiftGPU::PrintUsage () static protected
virtual SIFTGPU_EXPORT int SiftGPU::RunSIFT (const char * imgpath) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT int SiftGPU::RunSIFT (int index) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT int SiftGPU::RunSIFT (int width, int height, const void * data, unsigned int gl_format, unsigned int gl_type) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT int SiftGPU::RunSIFT () virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT int SiftGPU::RunSIFT (int num, const SiftKeypoint * keys, int keys_have_orientation = 1) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT void SiftGPU::SaveSIFT (const char * szFileName) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT void SiftGPU::SetActivePyramid (int index) inline virtual
Definition at line 187 of file SiftGPU.h.
virtual SIFTGPU_EXPORT void SiftGPU::SetImageList (int nimage, const char ** filelist) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT void SiftGPU::SetKeypointList (int num, const SiftKeypoint * keys, int keys_have_orientation = 1) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT void SiftGPU::SetMaxDimension (int sz) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT void SiftGPU::SetTightPyramid (int tight = 1) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT void SiftGPU::SetVerbose (int verbose = 4) virtual
Referenced by SetVerboseBrief().
void SiftGPU::SetVerboseBrief () inline
Definition at line 164 of file SiftGPU.h.
References SetVerbose().
virtual SIFTGPU_EXPORT int SiftGPU::VerifyContextGL () virtual
Reimplemented in ServerSiftGPU.
Member Data Documentation
int SiftGPU::_current protected
Definition at line 113 of file SiftGPU.h.
int SiftGPU::_image_loaded protected
Definition at line 119 of file SiftGPU.h.
char* SiftGPU::_imgpath protected
Definition at line 121 of file SiftGPU.h.
Referenced by GetCurrentImagePath().
int SiftGPU::_initialized protected
Definition at line 117 of file SiftGPU.h.
ImageList* SiftGPU::_list protected
Definition at line 125 of file SiftGPU.h.
char* SiftGPU::_outpath protected
Definition at line 123 of file SiftGPU.h.
SiftPyramid* SiftGPU::_pyramid protected
Definition at line 129 of file SiftGPU.h.
GLTexInput* SiftGPU::_texImage protected
Definition at line 127 of file SiftGPU.h.
float SiftGPU::_timing[10]
Definition at line 138 of file SiftGPU.h.
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/3rdparty/SiftGPU/src/SiftGPU/SiftGPU.h
This is a footer.
Pages generated on Mon Jun 29 2015 20:21:26