Open Detection: od::g3d::ODPointCloudGlobalMatchingDetector< PointT > Class Template Reference
od::g3d::ODPointCloudGlobalMatchingDetector< PointT > Class Template Reference
ODPointCloudGlobalMatchingDetector.
#include <ODPointCloudGlobalMatchingDetector.h>
Public Member Functions
ODPointCloudGlobalMatchingDetector (string const &training_data_location_="")
void init ()
ODDetections * detect (ODScenePointCloud< PointT > *scene)
ODDetections3D * detectOmni (ODScenePointCloud< PointT > *scene)
int getNN () const
void setNN (int NN)
string const & getDescName () const
void setDescName (string const &desc_name)
Public Member Functions inherited from od::ODDetector3D< PointT >
ODDetector3D (std::string const &training_data_location_)
Public Member Functions inherited from od::ODDetector
ODDetector (std::string const &training_data_location_)
virtual ODDetection * detect (ODScene *scene)
virtual ODDetections * detectOmni (ODScene *scene)
std::string getTrainingInputLocation () const
void setTrainingInputLocation (std::string training_input_location_)
std::string getTrainingDataLocation () const
void setTrainingDataLocation (std::string training_data_location_)
string getSpecificTrainingDataLocation ()
Protected Attributes
int NN
string desc_name
boost::shared_ptr
< pcl::rec_3d_framework::GlobalClassifier
< pcl::PointXYZ > > global_
Protected Attributes inherited from od::ODDetector
std::string training_input_location_
std::string training_data_location_
std::string TRAINED_DATA_EXT_
std::string TRAINED_DATA_IDENTIFIER_
Additional Inherited Members
Public Attributes inherited from od::ODDetector
bool metainfo_
Detailed Description
template<typename PointT = pcl::PointXYZRGBA>
class od::g3d::ODPointCloudGlobalMatchingDetector< PointT >
ODPointCloudGlobalMatchingDetector.
Author
Kripasindhu Sarkar
Definition at line 35 of file ODPointCloudGlobalMatchingDetector.h.
Constructor & Destructor Documentation
template<typename PointT = pcl::PointXYZRGBA> od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::ODPointCloudGlobalMatchingDetector (string const & training_data_location_ = "") inline
Definition at line 39 of file ODPointCloudGlobalMatchingDetector.h.
Member Function Documentation
template<typename PointT> ODDetections * od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::detect (ODScenePointCloud< PointT > * scene) virtual
Reimplemented from od::ODDetector3D< PointT >.
Definition at line 229 of file ODPointCloudGlobalMatchingDetector.h.
References od::ODScenePointCloud< PointType >::getPointCloud(), and od::ODDetections::push_back().
template<typename PointT> ODDetections3D * od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::detectOmni (ODScenePointCloud< PointT > * scene) virtual
Reimplemented from od::ODDetector3D< PointT >.
Definition at line 163 of file ODPointCloudGlobalMatchingDetector.h.
References od::ODScenePointCloud< PointType >::getPointCloud(), od::ODDetections::push_back(), od::ODDetection::setId(), od::ODDetection3D::setLocation(), od::ODDetection3D::setMetainfoCluster(), and od::ODDetection::setType().
template<typename PointT = pcl::PointXYZRGBA> string const& od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::getDescName () const inline
Definition at line 61 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT = pcl::PointXYZRGBA> int od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::getNN () const inline
Definition at line 51 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT > void od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::init () virtual
Implements od::ODDetector.
Definition at line 80 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT = pcl::PointXYZRGBA> void od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::setDescName (string const & desc_name) inline
Definition at line 66 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT = pcl::PointXYZRGBA> void od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::setNN (int NN) inline
Definition at line 56 of file ODPointCloudGlobalMatchingDetector.h.
Member Data Documentation
template<typename PointT = pcl::PointXYZRGBA> string od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::desc_name protected
Definition at line 73 of file ODPointCloudGlobalMatchingDetector.h.
Referenced by od::g3d::ODPointCloudGlobalMatchingDetector< pcl::PointXYZ >::getDescName(), and od::g3d::ODPointCloudGlobalMatchingDetector< pcl::PointXYZ >::setDescName().
template<typename PointT = pcl::PointXYZRGBA> boost::shared_ptr<pcl::rec_3d_framework::GlobalClassifier<pcl::PointXYZ> > od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::global_ protected
Definition at line 74 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT = pcl::PointXYZRGBA> int od::g3d::ODPointCloudGlobalMatchingDetector< PointT >::NN protected
Definition at line 72 of file ODPointCloudGlobalMatchingDetector.h.
Referenced by od::g3d::ODPointCloudGlobalMatchingDetector< pcl::PointXYZ >::getNN(), and od::g3d::ODPointCloudGlobalMatchingDetector< pcl::PointXYZ >::setNN().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/detectors/global3D/detection/ODPointCloudGlobalMatchingDetector.h
This is a footer.
Pages generated on Mon Aug 10 2015 14:49:07