Open Detection: GlobalUtil Class Reference
GlobalUtil Class Reference
#include <GlobalUtil.h>
Static Public Member Functions
static double CLOCK ()
static void StopTimer ()
static void StartTimer (const char *event)
static float GetElapsedTime ()
static void FitViewPort (int width, int height)
static void SetTextureParameter ()
static void SetTextureParameterUS ()
static void CheckErrorsGL (const char *location=NULL)
static bool CheckFramebufferStatus ()
static void SelectDisplay ()
static void InitGLParam (int NotTargetGL=0)
static void SetGLParam ()
static int CreateWindowEZ ()
static void CleanupOpenGL ()
static void SetDeviceParam (int argc, char **argv)
static int CreateWindowEZ (LiteWindow *window)
Additional Inherited Members
Static Public Attributes inherited from GlobalParam
static GLuint _texTarget
static GLuint _iTexFormat
static int _texMaxDim
static int _texMaxDimGL
static int _texMinDim
static int _MemCapGPU
static int _FitMemoryCap
static int _verbose
static int _timingS
static int _timingO
static int _timingL
static int _usePackedTex
static int _IsNvidia
static int _KeepShaderLoop
static int _UseCUDA
static int _UseOpenCL
static int _UseDynamicIndexing
static int _debug
static int _MaxFilterWidth
static float _FilterWidthFactor
static float _OrientationWindowFactor
static float _DescriptorWindowFactor
static int _MaxOrientation
static int _OrientationPack2
static int _ListGenGPU
static int _ListGenSkipGPU
static int _SupportNVFloat
static int _SupportTextureRG
static int _FullSupported
static float _MaxFeaturePercent
static int _MaxLevelFeatureNum
static int _DescriptorPPR
static int _DescriptorPPT
static int _FeatureTexBlock
static int _NarrowFeatureTex
static int _SubpixelLocalization
static int _ProcessOBO
static int _TruncateMethod
static int _PreciseBorder
static int _UseSiftGPUEX
static int _ForceTightPyramid
static int _octave_min_default
static int _octave_num_default
static int _InitPyramidWidth
static int _InitPyramidHeight
static int _PreProcessOnCPU
static int _GoodOpenGL
static int _FixedOrientation
static int _LoweOrigin
static int _ExitAfterSIFT
static int _NormalizedSIFT
static int _BinarySIFT
static int _KeepExtremumSign
static int _FeatureCountThreshold
static int _KeyPointListForceLevel0
static int _DarknessAdaption
static float _OrientationExtraFactor
static float _OrientationGaussianFactor
static float _MulitiOrientationThreshold
static int _WindowInitX
static int _WindowInitY
static const char * _WindowDisplay
static int _DeviceIndex
Detailed Description
Definition at line 122 of file GlobalUtil.h.
Member Function Documentation
static void GlobalUtil::CheckErrorsGL (const char * location = NULL) inline static
Definition at line 137 of file GlobalUtil.h.
static bool GlobalUtil::CheckFramebufferStatus () static
static void GlobalUtil::CleanupOpenGL () static
static double GlobalUtil::CLOCK () inline static
Definition at line 126 of file GlobalUtil.h.
References ClockTimer::CLOCK().
static int GlobalUtil::CreateWindowEZ () static
static int GlobalUtil::CreateWindowEZ (LiteWindow * window) static
static void GlobalUtil::FitViewPort (int width, int height) static
static float GlobalUtil::GetElapsedTime () inline static
Definition at line 129 of file GlobalUtil.h.
References ClockTimer::GetElapsedTime().
static void GlobalUtil::InitGLParam (int NotTargetGL = 0) static
static void GlobalUtil::SelectDisplay () static
static void GlobalUtil::SetDeviceParam (int argc, char ** argv) static
static void GlobalUtil::SetGLParam () static
static void GlobalUtil::SetTextureParameter () static
static void GlobalUtil::SetTextureParameterUS () static
static void GlobalUtil::StartTimer (const char * event) inline static
Definition at line 128 of file GlobalUtil.h.
References GlobalParam::_timingO, and ClockTimer::StartTimer().
static void GlobalUtil::StopTimer () inline static
Definition at line 127 of file GlobalUtil.h.
References GlobalParam::_timingS, and ClockTimer::StopTimer().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/3rdparty/SiftGPU/src/SiftGPU/GlobalUtil.h
This is a footer.
Pages generated on Mon Jun 29 2015 20:21:26