Open Detection: od::ODHOGMultiscaleDetector Class Reference
od::ODHOGMultiscaleDetector Class Reference
ODHOGMultiscaleDetector: A linear classifier detector for HOG features User can set any linear classifier through setSVMDetector function or one of the default available detectors like OD_DEFAULT_PEOPLE This class will then find HOG features in the scene and use the liniar classification model as an input to classify the scene It covers both simple region detection and omni detection (multiscale mitilocation detection on the entire scene)
#include <ODHOGMultiscaleDetector.h>
Public Member Functions
OD_DEFINE_ENUM_WITH_STRING_CONVERSIONS (SVMType,(OD_CUSTOM)(OD_DEFAULT_PEOPLE)(OD_DAIMLER_PEOPLE)) ODHOGMultiscaleDetector()
void init ()
void setSVMDetector (std::vector< float > svmdetector)
ODDetections2D * detect (ODSceneImage *scene)
int detect (ODScene *scene, vector< ODDetection * > &detections)
Detailed Description
ODHOGMultiscaleDetector: A linear classifier detector for HOG features User can set any linear classifier through setSVMDetector function or one of the default available detectors like OD_DEFAULT_PEOPLE This class will then find HOG features in the scene and use the liniar classification model as an input to classify the scene It covers both simple region detection and omni detection (multiscale mitilocation detection on the entire scene)
Author
Kripasindhu Sarkar
Definition at line 28 of file ODHOGMultiscaleDetector.h.
Member Function Documentation
ODDetections2D* od::ODHOGMultiscaleDetector::detect (ODSceneImage * scene) inline
Definition at line 55 of file ODHOGMultiscaleDetector.h.
References od::ODSceneImage::getCVImage(), od::ODDetector::metainfo_, od::ODDetections::push_back(), od::ODDetection2D::setBoundingBox(), and od::ODDetections::setMetainfoImage().
int od::ODHOGMultiscaleDetector::detect (ODScene * scene, vector< ODDetection * > & detections) inline
Definition at line 101 of file ODHOGMultiscaleDetector.h.
void od::ODHOGMultiscaleDetector::init () inline virtual
Reimplemented from od::ODAlgorithmBase.
Definition at line 40 of file ODHOGMultiscaleDetector.h.
od::ODHOGMultiscaleDetector::OD_DEFINE_ENUM_WITH_STRING_CONVERSIONS (SVMType , (OD_CUSTOM)(OD_DEFAULT_PEOPLE)(OD_DAIMLER_PEOPLE)) inline
Definition at line 32 of file ODHOGMultiscaleDetector.h.
References od::ODDetector::metainfo_.
void od::ODHOGMultiscaleDetector::setSVMDetector (std::vector< float > svmdetector) inline
Definition at line 50 of file ODHOGMultiscaleDetector.h.
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/detectors/global2D/detection/ODHOGMultiscaleDetector.h
This is a footer.
Pages generated on Sat Jul 18 2015 15:49:18