Open Detection: pugi::xml_node Class Reference
pugi::xml_node Class Reference
#include <pugixml.hpp>
Public Types
typedef xml_node_iterator iterator
typedef xml_attribute_iterator attribute_iterator
Public Member Functions
xml_node ()
xml_node (xml_node_struct *p)
operator unspecified_bool_type () const
bool operator! () const
bool operator== (const xml_node &r) const
bool operator!= (const xml_node &r) const
bool operator< (const xml_node &r) const
bool operator> (const xml_node &r) const
bool operator<= (const xml_node &r) const
bool operator>= (const xml_node &r) const
bool empty () const
xml_node_type type () const
const char_t * name () const
const char_t * value () const
xml_attribute first_attribute () const
xml_attribute last_attribute () const
xml_node first_child () const
xml_node last_child () const
xml_node next_sibling () const
xml_node previous_sibling () const
xml_node parent () const
xml_node root () const
xml_text text () const
xml_node child (const char_t *name) const
xml_attribute attribute (const char_t *name) const
xml_node next_sibling (const char_t *name) const
xml_node previous_sibling (const char_t *name) const
const char_t * child_value () const
const char_t * child_value (const char_t *name) const
bool set_name (const char_t *rhs)
bool set_value (const char_t *rhs)
xml_attribute append_attribute (const char_t *name)
xml_attribute prepend_attribute (const char_t *name)
xml_attribute insert_attribute_after (const char_t *name, const xml_attribute &attr)
xml_attribute insert_attribute_before (const char_t *name, const xml_attribute &attr)
xml_attribute append_copy (const xml_attribute &proto)
xml_attribute prepend_copy (const xml_attribute &proto)
xml_attribute insert_copy_after (const xml_attribute &proto, const xml_attribute &attr)
xml_attribute insert_copy_before (const xml_attribute &proto, const xml_attribute &attr)
xml_node append_child (xml_node_type type=node_element)
xml_node prepend_child (xml_node_type type=node_element)
xml_node insert_child_after (xml_node_type type, const xml_node &node)
xml_node insert_child_before (xml_node_type type, const xml_node &node)
xml_node append_child (const char_t *name)
xml_node prepend_child (const char_t *name)
xml_node insert_child_after (const char_t *name, const xml_node &node)
xml_node insert_child_before (const char_t *name, const xml_node &node)
xml_node append_copy (const xml_node &proto)
xml_node prepend_copy (const xml_node &proto)
xml_node insert_copy_after (const xml_node &proto, const xml_node &node)
xml_node insert_copy_before (const xml_node &proto, const xml_node &node)
xml_node append_move (const xml_node &moved)
xml_node prepend_move (const xml_node &moved)
xml_node insert_move_after (const xml_node &moved, const xml_node &node)
xml_node insert_move_before (const xml_node &moved, const xml_node &node)
bool remove_attribute (const xml_attribute &a)
bool remove_attribute (const char_t *name)
bool remove_child (const xml_node &n)
bool remove_child (const char_t *name)
xml_parse_result append_buffer (const void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
template<typename Predicate >
xml_attribute find_attribute (Predicate pred) const
template<typename Predicate >
xml_node find_child (Predicate pred) const
template<typename Predicate >
xml_node find_node (Predicate pred) const
xml_node find_child_by_attribute (const char_t *name, const char_t *attr_name, const char_t *attr_value) const
xml_node find_child_by_attribute (const char_t *attr_name, const char_t *attr_value) const
string_t path (char_t delimiter= '/') const
xml_node first_element_by_path (const char_t *path, char_t delimiter= '/') const
bool traverse (xml_tree_walker &walker)
xpath_node select_node (const char_t *query, xpath_variable_set *variables=0) const
xpath_node select_node (const xpath_query &query) const
xpath_node_set select_nodes (const char_t *query, xpath_variable_set *variables=0) const
xpath_node_set select_nodes (const xpath_query &query) const
xpath_node select_single_node (const char_t *query, xpath_variable_set *variables=0) const
xpath_node select_single_node (const xpath_query &query) const
void print (xml_writer &writer, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< char, std::char_traits< char > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, unsigned int depth=0) const
iterator begin () const
iterator end () const
attribute_iterator attributes_begin () const
attribute_iterator attributes_end () const
xml_object_range
< xml_node_iterator > children () const
xml_object_range
< xml_named_node_iterator > children (const char_t *name) const
xml_object_range
< xml_attribute_iterator > attributes () const
ptrdiff_t offset_debug () const
size_t hash_value () const
xml_node_struct * internal_object () const
Protected Types
typedef void(* unspecified_bool_type)(xml_node ***)
Protected Attributes
xml_node_struct * _root
Friends
class xml_attribute_iterator
class xml_node_iterator
class xml_named_node_iterator
Detailed Description
Definition at line 394 of file pugixml.hpp.
Member Typedef Documentation
typedef xml_attribute_iterator pugi::xml_node::attribute_iterator
Definition at line 619 of file pugixml.hpp.
typedef xml_node_iterator pugi::xml_node::iterator
Definition at line 613 of file pugixml.hpp.
typedef void(* pugi::xml_node::unspecified_bool_type)(xml_node ***) protected
Definition at line 403 of file pugixml.hpp.
Constructor & Destructor Documentation
pugi::xml_node::xml_node ()
pugi::xml_node::xml_node (xml_node_struct * p) explicit
Member Function Documentation
xml_attribute pugi::xml_node::append_attribute (const char_t * name)
xml_parse_result pugi::xml_node::append_buffer (const void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
xml_node pugi::xml_node::append_child (xml_node_type type = node_element)
xml_node pugi::xml_node::append_child (const char_t * name)
xml_attribute pugi::xml_node::append_copy (const xml_attribute & proto)
xml_node pugi::xml_node::append_copy (const xml_node & proto)
xml_node pugi::xml_node::append_move (const xml_node & moved)
xml_attribute pugi::xml_node::attribute (const char_t * name) const
xml_object_range<xml_attribute_iterator> pugi::xml_node::attributes () const
Referenced by pugi::attributes().
attribute_iterator pugi::xml_node::attributes_begin () const
attribute_iterator pugi::xml_node::attributes_end () const
iterator pugi::xml_node::begin () const
xml_node pugi::xml_node::child (const char_t * name) const
const char_t* pugi::xml_node::child_value () const
const char_t* pugi::xml_node::child_value (const char_t * name) const
xml_object_range<xml_node_iterator> pugi::xml_node::children () const
Referenced by pugi::children().
xml_object_range<xml_named_node_iterator> pugi::xml_node::children (const char_t * name) const
bool pugi::xml_node::empty () const
iterator pugi::xml_node::end () const
template<typename Predicate > xml_attribute pugi::xml_node::find_attribute (Predicate pred) const inline
Definition at line 526 of file pugixml.hpp.
References pugi::xml_attribute::next_attribute().
template<typename Predicate > xml_node pugi::xml_node::find_child (Predicate pred) const inline
Definition at line 538 of file pugixml.hpp.
References next_sibling().
xml_node pugi::xml_node::find_child_by_attribute (const char_t * name, const char_t * attr_name, const char_t * attr_value) const
xml_node pugi::xml_node::find_child_by_attribute (const char_t * attr_name, const char_t * attr_value) const
template<typename Predicate > xml_node pugi::xml_node::find_node (Predicate pred) const inline
Definition at line 550 of file pugixml.hpp.
References _root, first_child(), next_sibling(), and parent().
xml_attribute pugi::xml_node::first_attribute () const
xml_node pugi::xml_node::first_child () const
Referenced by find_node().
xml_node pugi::xml_node::first_element_by_path (const char_t * path, char_t delimiter = '/') const
size_t pugi::xml_node::hash_value () const
xml_attribute pugi::xml_node::insert_attribute_after (const char_t * name, const xml_attribute & attr)
xml_attribute pugi::xml_node::insert_attribute_before (const char_t * name, const xml_attribute & attr)
xml_node pugi::xml_node::insert_child_after (xml_node_type type, const xml_node & node)
xml_node pugi::xml_node::insert_child_after (const char_t * name, const xml_node & node)
xml_node pugi::xml_node::insert_child_before (xml_node_type type, const xml_node & node)
xml_node pugi::xml_node::insert_child_before (const char_t * name, const xml_node & node)
xml_attribute pugi::xml_node::insert_copy_after (const xml_attribute & proto, const xml_attribute & attr)
xml_node pugi::xml_node::insert_copy_after (const xml_node & proto, const xml_node & node)
xml_attribute pugi::xml_node::insert_copy_before (const xml_attribute & proto, const xml_attribute & attr)
xml_node pugi::xml_node::insert_copy_before (const xml_node & proto, const xml_node & node)
xml_node pugi::xml_node::insert_move_after (const xml_node & moved, const xml_node & node)
xml_node pugi::xml_node::insert_move_before (const xml_node & moved, const xml_node & node)
xml_node_struct* pugi::xml_node::internal_object () const
xml_attribute pugi::xml_node::last_attribute () const
xml_node pugi::xml_node::last_child () const
const char_t* pugi::xml_node::name () const
xml_node pugi::xml_node::next_sibling () const
Referenced by find_child(), and find_node().
xml_node pugi::xml_node::next_sibling (const char_t * name) const
ptrdiff_t pugi::xml_node::offset_debug () const
pugi::xml_node::operator unspecified_bool_type () const
bool pugi::xml_node::operator! () const
bool pugi::xml_node::operator!= (const xml_node & r) const
bool pugi::xml_node::operator< (const xml_node & r) const
bool pugi::xml_node::operator<= (const xml_node & r) const
bool pugi::xml_node::operator== (const xml_node & r) const
bool pugi::xml_node::operator> (const xml_node & r) const
bool pugi::xml_node::operator>= (const xml_node & r) const
xml_node pugi::xml_node::parent () const
Referenced by find_node().
string_t pugi::xml_node::path (char_t delimiter = '/') const
xml_attribute pugi::xml_node::prepend_attribute (const char_t * name)
xml_node pugi::xml_node::prepend_child (xml_node_type type = node_element)
xml_node pugi::xml_node::prepend_child (const char_t * name)
xml_attribute pugi::xml_node::prepend_copy (const xml_attribute & proto)
xml_node pugi::xml_node::prepend_copy (const xml_node & proto)
xml_node pugi::xml_node::prepend_move (const xml_node & moved)
xml_node pugi::xml_node::previous_sibling () const
xml_node pugi::xml_node::previous_sibling (const char_t * name) const
void pugi::xml_node::print (xml_writer & writer, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto, unsigned int depth = 0) const
void pugi::xml_node::print (std::basic_ostream< char, std::char_traits< char > > & os, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto, unsigned int depth = 0) const
void pugi::xml_node::print (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > & os, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, unsigned int depth = 0) const
bool pugi::xml_node::remove_attribute (const xml_attribute & a)
bool pugi::xml_node::remove_attribute (const char_t * name)
bool pugi::xml_node::remove_child (const xml_node & n)
bool pugi::xml_node::remove_child (const char_t * name)
xml_node pugi::xml_node::root () const
xpath_node pugi::xml_node::select_node (const char_t * query, xpath_variable_set * variables = 0) const
xpath_node pugi::xml_node::select_node (const xpath_query & query) const
xpath_node_set pugi::xml_node::select_nodes (const char_t * query, xpath_variable_set * variables = 0) const
xpath_node_set pugi::xml_node::select_nodes (const xpath_query & query) const
xpath_node pugi::xml_node::select_single_node (const char_t * query, xpath_variable_set * variables = 0) const
xpath_node pugi::xml_node::select_single_node (const xpath_query & query) const
bool pugi::xml_node::set_name (const char_t * rhs)
bool pugi::xml_node::set_value (const char_t * rhs)
xml_text pugi::xml_node::text () const
bool pugi::xml_node::traverse (xml_tree_walker & walker)
xml_node_type pugi::xml_node::type () const
const char_t* pugi::xml_node::value () const
Friends And Related Function Documentation
friend class xml_attribute_iterator friend
Definition at line 396 of file pugixml.hpp.
friend class xml_named_node_iterator friend
Definition at line 398 of file pugixml.hpp.
friend class xml_node_iterator friend
Definition at line 397 of file pugixml.hpp.
Member Data Documentation
xml_node_struct* pugi::xml_node::_root protected
Definition at line 401 of file pugixml.hpp.
Referenced by find_node().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/3rdparty/pugixml-1.6/src/pugixml.hpp
This is a footer.
Pages generated on Mon Jun 29 2015 20:21:26