Open Detection: od::FileUtils Class Reference
od::FileUtils Class Reference
Utility class for File and directory handling.
#include <utils.h>
Static Public Member Functions
static std::string getFirstFile (std::string base_path, std::string extension)
static void getFilesInDirectoryRec (std::string base_path, std::string extension, std::vector< std::string > &files)
static void getFilesInDirectoryRec (std::string base_path, std::vector< std::string > extensions, std::vector< std::string > &files)
static void getFilesInDirectoryInternal (bf::path &dir, std::string &rel_path_so_far, std::vector< std::string > &relative_paths, std::vector< std::string > exts)
static void getFilesInDirectoryInternal (bf::path &dir, std::string &rel_path_so_far, std::vector< std::string > &relative_paths, std::string const &ext)
static void getFilesInDirectory (bf::path &dir, std::string &rel_path_so_far, std::vector< std::string > &relative_paths, std::string const &ext)
static void createTrainingDir (std::string training_dir)
static void getArgvArgc (std::string const &commandline, char ***argv, int &argc)
Detailed Description
Utility class for File and directory handling.
Author
Kripasindhu Sarkar
Definition at line 170 of file utils.h.
Member Function Documentation
static void od::FileUtils::createTrainingDir (std::string training_dir) inline static
Definition at line 330 of file utils.h.
Referenced by od::g2d::ODHOGTrainer::ODHOGTrainer().
static void od::FileUtils::getArgvArgc (std::string const & commandline, char *** argv, int & argc) inline static
Definition at line 337 of file utils.h.
static void od::FileUtils::getFilesInDirectory (bf::path & dir, std::string & rel_path_so_far, std::vector< std::string > & relative_paths, std::string const & ext) inline static
Definition at line 290 of file utils.h.
References getFilesInDirectoryInternal().
static void od::FileUtils::getFilesInDirectoryInternal (bf::path & dir, std::string & rel_path_so_far, std::vector< std::string > & relative_paths, std::vector< std::string > exts) inline static
Definition at line 205 of file utils.h.
Referenced by getFilesInDirectory(), getFilesInDirectoryInternal(), getFilesInDirectoryRec(), and getFirstFile().
static void od::FileUtils::getFilesInDirectoryInternal (bf::path & dir, std::string & rel_path_so_far, std::vector< std::string > & relative_paths, std::string const & ext) inline static
Definition at line 250 of file utils.h.
References getFilesInDirectoryInternal().
static void od::FileUtils::getFilesInDirectoryRec (std::string base_path, std::string extension, std::vector< std::string > & files) inline static
Definition at line 189 of file utils.h.
References getFilesInDirectoryInternal().
static void od::FileUtils::getFilesInDirectoryRec (std::string base_path, std::vector< std::string > extensions, std::vector< std::string > & files) inline static
Definition at line 197 of file utils.h.
References getFilesInDirectoryInternal().
static std::string od::FileUtils::getFirstFile (std::string base_path, std::string extension) inline static
Definition at line 174 of file utils.h.
References getFilesInDirectoryInternal().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/common/utils/utils.h
Send your queries here.
Pages generated on Mon Aug 24 2015 17:06:15