Open Detection: od::ODDetection Class Reference
od::ODDetection Class Reference
The base class of all the detection.
#include <ODDetection.h>
Public Member Functions
OD_DEFINE_ENUM_WITH_STRING_CONVERSIONS (DetectionType,(OD_DETECTION_RECOG)(OD_DETECTION_CLASS)(OD_DETECTION_NULL)) virtual ~ODDetection()
ODDetection (DetectionType const &type_=OD_DETECTION_NULL, std::string const &id_="", double confidence_=1)
void printSelf ()
DetectionType const & getType () const
void setType (DetectionType const &type_)
std::string const & getId () const
void setId (std::string const &id_)
double getConfidence () const
Get/Set the confidence of the detection.
void setConfidence (double confidence_)
Get/Set the confidence of the detection.
Detailed Description
The base class of all the detection.
This is the base class of all the detection classes containing the detection information. All the ODDetector s return a collection of this class (in the form of ODDetections). Supports two modes: recognition (with type OD_DETECTION_RECOG) and classification (with type OD_DETECTION_CLASS). Along with the type, ODDetector sets an ID to identify what class or what instance of recognition is detected/recognied.
Author
Kripasindhu Sarkar
Definition at line 56 of file ODDetection.h.
Constructor & Destructor Documentation
od::ODDetection::ODDetection (DetectionType const & type_ = OD_DETECTION_NULL, std::string const & id_ = "", double confidence_ = 1) inline
Definition at line 66 of file ODDetection.h.
Member Function Documentation
double od::ODDetection::getConfidence () const inline
Get/Set the confidence of the detection.
ODDetector can use this to provide confidence amnong several detections.
Definition at line 99 of file ODDetection.h.
std::string const& od::ODDetection::getId () const inline
Examples:
objectdetector/od_multialgo_pc.cpp.
Definition at line 86 of file ODDetection.h.
DetectionType const& od::ODDetection::getType () const inline
Definition at line 76 of file ODDetection.h.
od::ODDetection::OD_DEFINE_ENUM_WITH_STRING_CONVERSIONS (DetectionType , (OD_DETECTION_RECOG)(OD_DETECTION_CLASS)(OD_DETECTION_NULL)) inline
Definition at line 61 of file ODDetection.h.
void od::ODDetection::printSelf () inline
Definition at line 70 of file ODDetection.h.
Referenced by od::ODDetection3D::printSelf().
void od::ODDetection::setConfidence (double confidence_) inline
Get/Set the confidence of the detection.
ODDetector can use this to provide confidence amnong several detections.
Definition at line 106 of file ODDetection.h.
void od::ODDetection::setId (std::string const & id_) inline
Definition at line 91 of file ODDetection.h.
Referenced by od::g3d::ODCADDetector3DGlobal< PointT >::detectOmni().
void od::ODDetection::setType (DetectionType const & type_) inline
Definition at line 81 of file ODDetection.h.
Referenced by od::g3d::ODCADDetector3DGlobal< PointT >::detectOmni().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/common/pipeline/ODDetection.h