Open Detection: SiftMatchGPU Class Reference
SiftMatchGPU Class Reference
matcher export
#include <SiftGPU.h>
Public Types
enum SIFTMATCH_LANGUAGE { SIFTMATCH_SAME_AS_SIFTGPU = 0, SIFTMATCH_GLSL = 2, SIFTMATCH_CUDA = 3, SIFTMATCH_CUDA_DEVICE0 = 3 }
Public Member Functions
int CreateContextGL ()
int VerifyContextGL ()
SIFTGPU_EXPORT SiftMatchGPU (int max_sift=4096)
virtual SIFTGPU_EXPORT void SetLanguage (int gpu_language)
virtual SIFTGPU_EXPORT void SetDeviceParam (int argc, char **argv)
virtual SIFTGPU_EXPORT void SetMaxSift (int max_sift)
virtual SIFTGPU_EXPORT ~SiftMatchGPU ()
virtual SIFTGPU_EXPORT void SetDescriptors (int index, int num, const float *descriptors, int id=-1)
virtual SIFTGPU_EXPORT void SetDescriptors (int index, int num, const unsigned char *descriptors, int id=-1)
virtual SIFTGPU_EXPORT int GetSiftMatch (int max_match, int match_buffer[][2], float distmax=0.7, float ratiomax=0.8, int mutual_best_match=1)
virtual SIFTGPU_EXPORT void SetFeautreLocation (int index, const float *locations, int gap=0)
void SetFeatureLocation (int index, const SiftGPU::SiftKeypoint *keys)
virtual SIFTGPU_EXPORT int GetGuidedSiftMatch (int max_match, int match_buffer[][2], float H[3][3], float F[3][3], float distmax=0.7, float ratiomax=0.8, float hdistmax=32, float fdistmax=16, int mutual_best_match=1)
SIFTGPU_EXPORT void * operator new (size_t size)
Protected Member Functions
virtual SIFTGPU_EXPORT int _CreateContextGL ()
virtual SIFTGPU_EXPORT int _VerifyContextGL ()
Detailed Description
matcher export
Definition at line 255 of file SiftGPU.h.
Member Enumeration Documentation
enum SiftMatchGPU::SIFTMATCH_LANGUAGE
Enumerator
SIFTMATCH_SAME_AS_SIFTGPU
SIFTMATCH_GLSL
SIFTMATCH_CUDA
SIFTMATCH_CUDA_DEVICE0
Definition at line 258 of file SiftGPU.h.
Constructor & Destructor Documentation
SIFTGPU_EXPORT SiftMatchGPU::SiftMatchGPU (int max_sift = 4096)
virtual SIFTGPU_EXPORT SiftMatchGPU::~SiftMatchGPU () virtual
Member Function Documentation
virtual SIFTGPU_EXPORT int SiftMatchGPU::_CreateContextGL () protected virtual
Reimplemented in ServerSiftGPU.
Referenced by CreateContextGL().
virtual SIFTGPU_EXPORT int SiftMatchGPU::_VerifyContextGL () protected virtual
Reimplemented in ServerSiftGPU.
Referenced by VerifyContextGL().
int SiftMatchGPU::CreateContextGL () inline
Definition at line 275 of file SiftGPU.h.
References _CreateContextGL().
virtual SIFTGPU_EXPORT int SiftMatchGPU::GetGuidedSiftMatch (int max_match, int match_buffer[][2], float H[3][3], float F[3][3], float distmax = 0.7, float ratiomax = 0.8, float hdistmax = 32, float fdistmax = 16, int mutual_best_match = 1) virtual
Reimplemented in ServerSiftGPU, and SiftMatchGL.
virtual SIFTGPU_EXPORT int SiftMatchGPU::GetSiftMatch (int max_match, int match_buffer[][2], float distmax = 0.7, float ratiomax = 0.8, int mutual_best_match = 1) virtual
Reimplemented in ServerSiftGPU, and SiftMatchGL.
SIFTGPU_EXPORT void* SiftMatchGPU::operator new (size_t size)
virtual SIFTGPU_EXPORT void SiftMatchGPU::SetDescriptors (int index, int num, const float * descriptors, int id = -1) virtual
Reimplemented in ServerSiftGPU, and SiftMatchGL.
virtual SIFTGPU_EXPORT void SiftMatchGPU::SetDescriptors (int index, int num, const unsigned char * descriptors, int id = -1) virtual
Reimplemented in ServerSiftGPU, and SiftMatchGL.
virtual SIFTGPU_EXPORT void SiftMatchGPU::SetDeviceParam (int argc, char ** argv) virtual
Reimplemented in ServerSiftGPU.
void SiftMatchGPU::SetFeatureLocation (int index, const SiftGPU::SiftKeypoint * keys) inline
Definition at line 316 of file SiftGPU.h.
References SetFeautreLocation().
virtual SIFTGPU_EXPORT void SiftMatchGPU::SetFeautreLocation (int index, const float * locations, int gap = 0) virtual
Reimplemented in ServerSiftGPU, and SiftMatchGL.
Referenced by SetFeatureLocation().
virtual SIFTGPU_EXPORT void SiftMatchGPU::SetLanguage (int gpu_language) virtual
Reimplemented in ServerSiftGPU.
virtual SIFTGPU_EXPORT void SiftMatchGPU::SetMaxSift (int max_sift) virtual
Reimplemented in ServerSiftGPU, and SiftMatchGL.
int SiftMatchGPU::VerifyContextGL () inline
Definition at line 276 of file SiftGPU.h.
References _VerifyContextGL().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/3rdparty/SiftGPU/src/SiftGPU/SiftGPU.h
This is a footer.
Pages generated on Mon Jun 29 2015 20:21:26