Open Detection: ServerSiftGPU Class Reference
ServerSiftGPU Class Reference
#include <ServerSiftGPU.h>
Public Member Functions
SIFTGPU_EXPORT ServerSiftGPU (int port=DEFAULT_PORT, char *remote_server=NULL)
virtual ~ServerSiftGPU ()
virtual void ParseParam (int argc, char **argv)
virtual int VerifyContextGL ()
virtual int RunSIFT (const char *imgpath)
virtual int RunSIFT ()
virtual int RunSIFT (int width, int height, const void *data, unsigned int gl_format, unsigned int gl_type)
virtual int RunSIFT (int num, const SiftGPU::SiftKeypoint *keys, int keys_have_orientation=1)
virtual int AllocatePyramid (int width, int height)
virtual int GetFeatureNum ()
virtual void SetTightPyramid (int tight=1)
virtual void SetMaxDimension (int sz)
virtual void GetFeatureVector (SiftGPU::SiftKeypoint *keys, float *descriptors)
virtual void SetKeypointList (int num, const SiftGPU::SiftKeypoint *keys, int keys_have_orientation=1)
virtual void SaveSIFT (const char *szFileName)
int GetImageCount ()
int CreateContextGL ()
int IsFullSupported ()
int RunSIFT (int index)
virtual int _CreateContextGL ()
virtual int _VerifyContextGL ()
virtual void SetLanguage (int gpu_language)
virtual void SetDeviceParam (int argc, char **argv)
virtual void SetMaxSift (int max_sift)
virtual void SetDescriptors (int index, int num, const float *descriptors, int id=-1)
virtual void SetDescriptors (int index, int num, const unsigned char *descriptors, int id=-1)
virtual int GetSiftMatch (int max_match, int match_buffer[][2], float distmax, float ratiomax, int mutual_best_match)
void SetImageList (int nimage, const char **filelist)
void SetVerbose ()
virtual void SetFeautreLocation (int index, const float *locations, int gap)
Guided matching is not supported here, not hard to implement yourself.
virtual int GetGuidedSiftMatch (int max_match, int match_buffer[][2], float H[3][3], float F[3][3], float distmax, float ratiomax, float hdistmax, float fdistmax, int mutual_best_match)
Public Member Functions inherited from ComboSiftGPU
SIFTGPU_EXPORT void * operator new (size_t size)
Public Member Functions inherited from SiftGPU
const char * GetCurrentImagePath ()
virtual SIFTGPU_EXPORT void SetVerbose (int verbose=4)
void SetVerboseBrief ()
SIFTGPU_EXPORT SiftGPU (int np=1)
virtual SIFTGPU_EXPORT ~SiftGPU ()
virtual SIFTGPU_EXPORT void SetActivePyramid (int index)
SIFTGPU_EXPORT void * operator new (size_t size)
Public Member Functions inherited from SiftParam
void ParseSiftParam ()
float GetLevelSigma (int lev)
float GetInitialSmoothSigma (int octave_min)
SIFTGPU_EXPORT SiftParam ()
Public Member Functions inherited from SiftMatchGPU
int CreateContextGL ()
int VerifyContextGL ()
SIFTGPU_EXPORT SiftMatchGPU (int max_sift=4096)
virtual SIFTGPU_EXPORT ~SiftMatchGPU ()
void SetFeatureLocation (int index, const SiftGPU::SiftKeypoint *keys)
SIFTGPU_EXPORT void * operator new (size_t size)
Friends
void RunServerLoop (int port, int argc, char **argv)
Additional Inherited Members
Public Types inherited from SiftGPU
enum { SIFTGPU_NOT_SUPPORTED = 0, SIFTGPU_PARTIAL_SUPPORTED = 1, SIFTGPU_FULL_SUPPORTED = 2 }
typedef struct
SiftGPU::SiftKeypoint SiftKeypoint
Public Types inherited from SiftMatchGPU
enum SIFTMATCH_LANGUAGE { SIFTMATCH_SAME_AS_SIFTGPU = 0, SIFTMATCH_GLSL = 2, SIFTMATCH_CUDA = 3, SIFTMATCH_CUDA_DEVICE0 = 3 }
Public Attributes inherited from SiftGPU
float _timing [10]
Public Attributes inherited from SiftParam
float * _sigma
float _sigma_skip0
float _sigma_skip1
float _sigma0
float _sigman
int _sigma_num
int _dog_level_num
int _level_num
int _level_min
int _level_max
int _level_ds
float _dog_threshold
float _edge_threshold
Protected Member Functions inherited from SiftGPU
void InitSiftGPU ()
void LoadImageList (const char *imlist)
Static Protected Member Functions inherited from SiftGPU
static void PrintUsage ()
Protected Attributes inherited from SiftGPU
int _current
int _initialized
int _image_loaded
char * _imgpath
char * _outpath
ImageList * _list
GLTexInput * _texImage
SiftPyramid * _pyramid
Detailed Description
Definition at line 45 of file ServerSiftGPU.h.
Constructor & Destructor Documentation
SIFTGPU_EXPORT ServerSiftGPU::ServerSiftGPU (int port = DEFAULT_PORT, char * remote_server = NULL)
virtual ServerSiftGPU::~ServerSiftGPU () virtual
Member Function Documentation
virtual int ServerSiftGPU::_CreateContextGL () inline virtual
Reimplemented from SiftMatchGPU.
Definition at line 131 of file ServerSiftGPU.h.
References _VerifyContextGL().
virtual int ServerSiftGPU::_VerifyContextGL () virtual
Reimplemented from SiftMatchGPU.
Referenced by _CreateContextGL().
virtual int ServerSiftGPU::AllocatePyramid (int width, int height) virtual
Reimplemented from SiftGPU.
int ServerSiftGPU::CreateContextGL () inline virtual
Reimplemented from SiftGPU.
Definition at line 125 of file ServerSiftGPU.h.
References VerifyContextGL().
virtual int ServerSiftGPU::GetFeatureNum () virtual
Reimplemented from SiftGPU.
virtual void ServerSiftGPU::GetFeatureVector (SiftGPU::SiftKeypoint * keys, float * descriptors) virtual
Reimplemented from SiftGPU.
virtual int ServerSiftGPU::GetGuidedSiftMatch (int max_match, int match_buffer[][2], float H[3][3], float F[3][3], float distmax, float ratiomax, float hdistmax, float fdistmax, int mutual_best_match) inline virtual
Reimplemented from SiftMatchGPU.
Definition at line 148 of file ServerSiftGPU.h.
int ServerSiftGPU::GetImageCount () inline virtual
Reimplemented from SiftGPU.
Definition at line 124 of file ServerSiftGPU.h.
virtual int ServerSiftGPU::GetSiftMatch (int max_match, int match_buffer[][2], float distmax, float ratiomax, int mutual_best_match) virtual
Reimplemented from SiftMatchGPU.
int ServerSiftGPU::IsFullSupported () inline virtual
Reimplemented from SiftGPU.
Definition at line 126 of file ServerSiftGPU.h.
References SiftGPU::SIFTGPU_FULL_SUPPORTED, and VerifyContextGL().
virtual void ServerSiftGPU::ParseParam (int argc, char ** argv) virtual
Reimplemented from SiftGPU.
virtual int ServerSiftGPU::RunSIFT (const char * imgpath) virtual
Reimplemented from SiftGPU.
virtual int ServerSiftGPU::RunSIFT () virtual
Reimplemented from SiftGPU.
virtual int ServerSiftGPU::RunSIFT (int width, int height, const void * data, unsigned int gl_format, unsigned int gl_type) virtual
Reimplemented from SiftGPU.
virtual int ServerSiftGPU::RunSIFT (int num, const SiftGPU::SiftKeypoint * keys, int keys_have_orientation = 1) virtual
Reimplemented from SiftGPU.
int ServerSiftGPU::RunSIFT (int index) inline virtual
Reimplemented from SiftGPU.
Definition at line 127 of file ServerSiftGPU.h.
References RunSIFT().
Referenced by RunSIFT().
virtual void ServerSiftGPU::SaveSIFT (const char * szFileName) virtual
Reimplemented from SiftGPU.
virtual void ServerSiftGPU::SetDescriptors (int index, int num, const float * descriptors, int id = -1) virtual
Reimplemented from SiftMatchGPU.
virtual void ServerSiftGPU::SetDescriptors (int index, int num, const unsigned char * descriptors, int id = -1) virtual
Reimplemented from SiftMatchGPU.
virtual void ServerSiftGPU::SetDeviceParam (int argc, char ** argv) virtual
Reimplemented from SiftMatchGPU.
virtual void ServerSiftGPU::SetFeautreLocation (int index, const float * locations, int gap) inline virtual
Guided matching is not supported here, not hard to implement yourself.
Reimplemented from SiftMatchGPU.
Definition at line 147 of file ServerSiftGPU.h.
void ServerSiftGPU::SetImageList (int nimage, const char ** filelist) inline virtual
Reimplemented from SiftGPU.
Definition at line 143 of file ServerSiftGPU.h.
virtual void ServerSiftGPU::SetKeypointList (int num, const SiftGPU::SiftKeypoint * keys, int keys_have_orientation = 1) virtual
Reimplemented from SiftGPU.
virtual void ServerSiftGPU::SetLanguage (int gpu_language) virtual
Reimplemented from SiftMatchGPU.
virtual void ServerSiftGPU::SetMaxDimension (int sz) virtual
Reimplemented from SiftGPU.
virtual void ServerSiftGPU::SetMaxSift (int max_sift) virtual
Reimplemented from SiftMatchGPU.
virtual void ServerSiftGPU::SetTightPyramid (int tight = 1) virtual
Reimplemented from SiftGPU.
void ServerSiftGPU::SetVerbose () inline
Definition at line 144 of file ServerSiftGPU.h.
virtual int ServerSiftGPU::VerifyContextGL () virtual
Reimplemented from SiftGPU.
Referenced by CreateContextGL(), and IsFullSupported().
Friends And Related Function Documentation
void RunServerLoop (int port, int argc, char ** argv) friend
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/3rdparty/SiftGPU/src/ServerSiftGPU/ServerSiftGPU.h
This is a footer.
Pages generated on Mon Jun 29 2015 20:21:26