Open Detection: ClockTimer Class Reference
ClockTimer Class Reference
#include <GlobalUtil.h>
Public Member Functions
void StopTimer (int verb=1)
void StartTimer (const char *event, int verb=0)
float GetElapsedTime ()
Static Public Member Functions
static int ClockMS ()
static double CLOCK ()
static void InitHighResolution ()
Detailed Description
Definition at line 107 of file GlobalUtil.h.
Member Function Documentation
static double ClockTimer::CLOCK () static
Referenced by GlobalUtil::CLOCK().
static int ClockTimer::ClockMS () static
float ClockTimer::GetElapsedTime ()
Referenced by GlobalUtil::GetElapsedTime().
static void ClockTimer::InitHighResolution () static
void ClockTimer::StartTimer (const char * event, int verb = 0)
Referenced by GlobalUtil::StartTimer().
void ClockTimer::StopTimer (int verb = 1)
Referenced by GlobalUtil::StopTimer().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/3rdparty/SiftGPU/src/SiftGPU/GlobalUtil.h
This is a footer.
Pages generated on Mon Jun 29 2015 20:21:26