Open Detection: Model Class Reference
Model Class Reference
#include <Model.h>
Public Member Functions
Model ()
virtual ~Model ()
std::vector< cv::Point2f > get_points2d_in () const
std::vector< cv::Point2f > get_points2d_out () const
std::vector< cv::Point3f > get_points3d () const
std::vector< cv::KeyPoint > get_keypoints () const
cv::Mat get_descriptors () const
int get_numDescriptors () const
void add_correspondence (const cv::Point2f &point2d, const cv::Point3f &point3d)
void add_outlier (const cv::Point2f &point2d)
void add_descriptor (const cv::Mat &descriptor)
void add_keypoint (const cv::KeyPoint &kp)
void save (const std::string path)
void load (const std::string path)
void load_new_desc (const std::string path)
void load_new_xml (const std::string path)
Public Attributes
std::string f_type
std::string id
Detailed Description
Definition at line 16 of file Model.h.
Constructor & Destructor Documentation
Model::Model ()
virtual Model::~Model () virtual
Member Function Documentation
void Model::add_correspondence (const cv::Point2f & point2d, const cv::Point3f & point3d)
void Model::add_descriptor (const cv::Mat & descriptor)
void Model::add_keypoint (const cv::KeyPoint & kp)
void Model::add_outlier (const cv::Point2f & point2d)
cv::Mat Model::get_descriptors () const inline
Definition at line 26 of file Model.h.
Referenced by od::SimpleRansacDetector::detectSingleModel().
std::vector<cv::KeyPoint> Model::get_keypoints () const inline
Definition at line 25 of file Model.h.
Referenced by od::SimpleRansacDetector::detectSingleModel().
int Model::get_numDescriptors () const inline
Definition at line 27 of file Model.h.
std::vector<cv::Point2f> Model::get_points2d_in () const inline
Definition at line 22 of file Model.h.
std::vector<cv::Point2f> Model::get_points2d_out () const inline
Definition at line 23 of file Model.h.
std::vector<cv::Point3f> Model::get_points3d () const inline
Definition at line 24 of file Model.h.
Referenced by od::SimpleRansacDetector::detectSingleModel().
void Model::load (const std::string path)
void Model::load_new_desc (const std::string path)
void Model::load_new_xml (const std::string path)
Referenced by od::SimpleRansacDetector::init().
void Model::save (const std::string path)
Member Data Documentation
std::string Model::f_type
Definition at line 42 of file Model.h.
std::string Model::id
Definition at line 43 of file Model.h.
Referenced by od::SimpleRansacDetector::detectSingleModel().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/detectors/image_local/detection/simple_ransac_detection/Model.h
This is a footer.
Pages generated on Mon Jun 15 2015 22:35:04