Open Detection: od::ODFeatureDetector2D Class Reference
od::ODFeatureDetector2D Class Reference
#include <ODFeatureDetector2D.h>
Public Types
enum FeatureType {
SIFT, SURF, ORB, SIFT_GPU,
ORB_GPU
}
Public Member Functions
ODFeatureDetector2D (std::string feature_type, bool use_gpu)
ODFeatureDetector2D (FeatureType type)
void computeKeypointsAndDescriptors (cv::Mat const &image, cv::Mat &descriptors, std::vector< cv::KeyPoint > &keypoints)
void findSiftGPUDescriptors (char const *image_name, cv::Mat &descriptors, std::vector< cv::KeyPoint > &keypoints)
void findSiftGPUDescriptors (cv::Mat const &image, cv::Mat &descriptors, std::vector< cv::KeyPoint > &keypoints)
Public Attributes
int mode_
Detailed Description
Definition at line 21 of file ODFeatureDetector2D.h.
Member Enumeration Documentation
enum od::ODFeatureDetector2D::FeatureType
Enumerator
SIFT
SURF
ORB
SIFT_GPU
ORB_GPU
Definition at line 27 of file ODFeatureDetector2D.h.
Constructor & Destructor Documentation
od::ODFeatureDetector2D::ODFeatureDetector2D (std::string feature_type, bool use_gpu)
od::ODFeatureDetector2D::ODFeatureDetector2D (FeatureType type) inline
Definition at line 34 of file ODFeatureDetector2D.h.
References computeKeypointsAndDescriptors(), findSiftGPUDescriptors(), mode_, ORB, ORB_GPU, SIFT, SIFT_GPU, and SURF.
Member Function Documentation
void od::ODFeatureDetector2D::computeKeypointsAndDescriptors (cv::Mat const & image, cv::Mat & descriptors, std::vector< cv::KeyPoint > & keypoints)
Referenced by ODFeatureDetector2D().
void od::ODFeatureDetector2D::findSiftGPUDescriptors (char const * image_name, cv::Mat & descriptors, std::vector< cv::KeyPoint > & keypoints)
Referenced by ODFeatureDetector2D().
void od::ODFeatureDetector2D::findSiftGPUDescriptors (cv::Mat const & image, cv::Mat & descriptors, std::vector< cv::KeyPoint > & keypoints)
Member Data Documentation
int od::ODFeatureDetector2D::mode_
Definition at line 32 of file ODFeatureDetector2D.h.
Referenced by ODFeatureDetector2D().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/common/utils/ODFeatureDetector2D.h
Send your queries here.
Pages generated on Mon Aug 24 2015 17:06:15