Open Detection: od::ODPointCloudGlobalMatchingDetector< PointT > Class Template Reference
od::ODPointCloudGlobalMatchingDetector< PointT > Class Template Reference
ODPointCloudGlobalMatchingDetector.
#include <ODPointCloudGlobalMatchingDetector.h>
Public Member Functions
ODPointCloudGlobalMatchingDetector (string const &training_data_location_="")
void init ()
int detect (ODScene *scene, vector< ODDetection * > &detections)
int detect (ODScenePointCloud< PointT > *scene, vector< ODDetection3D * > &detections)
int getNN () const
void setNN (int NN)
string const & getDescName () const
void setDescName (string const &desc_name)
Public Member Functions inherited from od::ODDetector
ODDetector ()
ODDetector (std::string const &training_data_location_)
virtual int detect (ODScene *scene, std::vector< ODDetection * > &detections)=0
virtual ODDetections * detect (ODScene *scene)
std::string getTrainingInputLocation () const
void setTrainingInputLocation (std::string training_input_location_)
std::string getTrainingDataLocation () const
void setTrainingDataLocation (std::string training_data_location_)
Public Member Functions inherited from od::ODAlgorithmBase
void getFilesInDirectory (bf::path &dir, std::string &rel_path_so_far, std::vector< std::string > &relative_paths, std::string const &ext)
void createTrainingDir (std::string &training_dir)
void getArgvArgc (std::string const &commandline, char ***argv, int &argc)
virtual void parseParameterString (std::string parameter_string)
Protected Attributes
int NN
string desc_name
boost::shared_ptr
< pcl::rec_3d_framework::GlobalClassifier
< pcl::PointXYZ > > global_
Protected Attributes inherited from od::ODDetector
std::string training_input_location_
std::string training_data_location_
Additional Inherited Members
Public Attributes inherited from od::ODDetector
bool metainfo_
Detailed Description
template<typename PointT = pcl::PointXYZRGBA>
class od::ODPointCloudGlobalMatchingDetector< PointT >
ODPointCloudGlobalMatchingDetector.
Author
Kripasindhu Sarkar
Definition at line 33 of file ODPointCloudGlobalMatchingDetector.h.
Constructor & Destructor Documentation
template<typename PointT = pcl::PointXYZRGBA> od::ODPointCloudGlobalMatchingDetector< PointT >::ODPointCloudGlobalMatchingDetector (string const & training_data_location_ = "") inline
Definition at line 37 of file ODPointCloudGlobalMatchingDetector.h.
Member Function Documentation
template<typename PointT = pcl::PointXYZRGBA> int od::ODPointCloudGlobalMatchingDetector< PointT >::detect (ODScene * scene, vector< ODDetection * > & detections) inline
Definition at line 42 of file ODPointCloudGlobalMatchingDetector.h.
Referenced by od::ODPointCloudGlobalMatchingDetector< pcl::PointXYZ >::detect().
template<typename PointT> int od::ODPointCloudGlobalMatchingDetector< PointT >::detect (ODScenePointCloud< PointT > * scene, vector< ODDetection3D * > & detections)
Definition at line 159 of file ODPointCloudGlobalMatchingDetector.h.
References od::ODScenePointCloud< PointType >::getPointCloud(), od::ODDetection3D::setLocation(), and od::ODDetection3D::setMetainfoCluster().
template<typename PointT = pcl::PointXYZRGBA> string const& od::ODPointCloudGlobalMatchingDetector< PointT >::getDescName () const inline
Definition at line 61 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT = pcl::PointXYZRGBA> int od::ODPointCloudGlobalMatchingDetector< PointT >::getNN () const inline
Definition at line 51 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT > void od::ODPointCloudGlobalMatchingDetector< PointT >::init () virtual
Reimplemented from od::ODAlgorithmBase.
Definition at line 80 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT = pcl::PointXYZRGBA> void od::ODPointCloudGlobalMatchingDetector< PointT >::setDescName (string const & desc_name) inline
Definition at line 66 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT = pcl::PointXYZRGBA> void od::ODPointCloudGlobalMatchingDetector< PointT >::setNN (int NN) inline
Definition at line 56 of file ODPointCloudGlobalMatchingDetector.h.
Member Data Documentation
template<typename PointT = pcl::PointXYZRGBA> string od::ODPointCloudGlobalMatchingDetector< PointT >::desc_name protected
Definition at line 73 of file ODPointCloudGlobalMatchingDetector.h.
Referenced by od::ODPointCloudGlobalMatchingDetector< pcl::PointXYZ >::getDescName(), and od::ODPointCloudGlobalMatchingDetector< pcl::PointXYZ >::setDescName().
template<typename PointT = pcl::PointXYZRGBA> boost::shared_ptr<pcl::rec_3d_framework::GlobalClassifier<pcl::PointXYZ> > od::ODPointCloudGlobalMatchingDetector< PointT >::global_ protected
Definition at line 74 of file ODPointCloudGlobalMatchingDetector.h.
template<typename PointT = pcl::PointXYZRGBA> int od::ODPointCloudGlobalMatchingDetector< PointT >::NN protected
Definition at line 72 of file ODPointCloudGlobalMatchingDetector.h.
Referenced by od::ODPointCloudGlobalMatchingDetector< pcl::PointXYZ >::getNN(), and od::ODPointCloudGlobalMatchingDetector< pcl::PointXYZ >::setNN().
The documentation for this class was generated from the following file:
/home/sarkar/opendetection/detectors/global3D/detection/ODPointCloudGlobalMatchingDetector.h
This is a footer.
Pages generated on Wed Jul 22 2015 11:55:41