var NAVTREEINDEX2 =
{
"namespacesvmlight.html":[1,1,0,1],
"namespacesvmlight.html":[1,0,0,1],
"objectdetector_2od_hog_train_8cpp-example.html":[1,2,1],
"objectdetector_2od_image_cadrecog_camera_8cpp-example.html":[1,2,2],
"objectdetector_2od_image_cadrecog_files_8cpp-example.html":[1,2,3],
"objectdetector_2od_image_cascade_8cpp-example.html":[1,2,4],
"objectdetector_2od_image_cascade_files_8cpp-example.html":[1,2,5],
"objectdetector_2od_image_facerecog_8cpp-example.html":[1,2,6],
"objectdetector_2od_image_hog_8cpp-example.html":[1,2,7],
"objectdetector_2od_image_hog_files_8cpp-example.html":[1,2,8],
"objectdetector_2od_multialgo_files_8cpp-example.html":[1,2,9],
"objectdetector_2od_multialgo_pc_8cpp-example.html":[1,2,10],
"objectdetector_2od_pc_global_files_8cpp-example.html":[1,2,11],
"objectdetector_2od_pc_global_real_time_8cpp-example.html":[1,2,12],
"pages.html":[],
"tutorial_root.html":[0],
"usergroup0.html":[1],
"writing_a_new_app.html":[0,6],
"writing_a_new_app.html#writing_a_new_app1":[0,6,0]
};
