var NAVTREEINDEX2 =
{
"namespaces.html":[2,0],
"namespacesvmlight.html":[2,0,1],
"namespacesvmlight.html":[3,0,1],
"objectdetector_2od_hog_train_8cpp-example.html":[4,1],
"objectdetector_2od_image_cadrecog_camera_8cpp-example.html":[4,2],
"objectdetector_2od_image_cadrecog_files_8cpp-example.html":[4,3],
"objectdetector_2od_image_cascade_8cpp-example.html":[4,4],
"objectdetector_2od_image_cascade_files_8cpp-example.html":[4,5],
"objectdetector_2od_image_facerecog_8cpp-example.html":[4,6],
"objectdetector_2od_image_hog_8cpp-example.html":[4,7],
"objectdetector_2od_image_hog_files_8cpp-example.html":[4,8],
"objectdetector_2od_multialgo_files_8cpp-example.html":[4,9],
"objectdetector_2od_multialgo_pc_8cpp-example.html":[4,10],
"objectdetector_2od_pc_global_files_8cpp-example.html":[4,11],
"objectdetector_2od_pc_global_real_time_8cpp-example.html":[4,12],
"pages.html":[],
"tutorial_root.html":[1],
"writing_a_new_app.html":[1,6],
"writing_a_new_app.html#writing_a_new_app1":[1,6,0]
};
